remote_theme: mmistakes/minimal-mistakes@4.24.0 # Change version as needed

title: "Ben FrantzDale's Blog"
description: "A blog about software, engineering, and more."
url: "https://benfrantzdale.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge