title: "Ben FrantzDale's Blog"
description: "A blog about software, engineering, and more."
url: "https://benfrantzdale.github.io"
baseurl: ""
theme: minimal-mistakes-jekyll
markdown: kramdown
highlighter: rouge